import json
import glob
import numpy as np

nat=39

#O1 is O near O2 is O far

files=glob.glob("window*.xyz")

order={}
for file in files:
    name="".join([file.split('_')[1][x] for x in range(3)])
    order[name]={"O1":0,"O2":0}
    struct=[]
    O=[]
    dists=[]
    with open(file,'r') as ifile:
        lines=ifile.readlines()
    for i,line in enumerate(lines):
        if "generated by VMD" in line:
            last=i
    print(last)
    for j in range(last,last+nat):
        try:
            struct.append(lines[j])
        except:
            print(j,file)
    for i,line in enumerate(struct):
        if 'Mg' in line:
            MG=[float(line.split()[i]) for i in range(1,4)]
        if 'O' in line:
            O.append(([float(line.split()[i]) for i in range(1,4)],i))
    for atom in O:
        dist=np.linalg.norm(np.array(atom[0])-np.array(MG))
        dists.append(dist)
    for i,item in enumerate(dists):
        if item == min(dists):
            O[i]=O[i]+(1,0)
        else:
            O[i]=O[i]+(2,0)
    for item in O:
        if item[2] == 1:
            order[name]["O1"]=item[1]
        else:
            order[name]["O2"]=item[1]
            
        
with open('order.json','w') as ofile:
    json.dump(order,ofile)
            
        
